package com.hong.bean;

public class Ptype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptype.id
     *
     * @mbg.generated Wed Apr 04 11:21:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptype.name
     *
     * @mbg.generated Wed Apr 04 11:21:10 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptype.id
     *
     * @return the value of ptype.id
     *
     * @mbg.generated Wed Apr 04 11:21:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptype.id
     *
     * @param id the value for ptype.id
     *
     * @mbg.generated Wed Apr 04 11:21:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptype.name
     *
     * @return the value of ptype.name
     *
     * @mbg.generated Wed Apr 04 11:21:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptype.name
     *
     * @param name the value for ptype.name
     *
     * @mbg.generated Wed Apr 04 11:21:10 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}